### ISSUE TITLE
Display freezes when multiple matrixes are connected.

### ISSUE THREAD

**Issue by Boaztheostrich** [lyriarte/StripDisplay#1]
My code is attached below all matrixes are confirmed to work. I am running this on an arduino nano. The memory is not full.

#define FONT_5x8_FIXED_MEDIUM
#define FONT_CHARSET_SMALL
#include <StripDisplay.h>
XBMFont * fontP = &fixedMedium_5x8;

#define Brake       2
#define Running 4
#define Turn 5
#define Reverse 3

// Connections to the LED strips
#define Tur     10
#define Rev 8
#define Run_b 6 
#define STRIPLED_GPIO 7
#define Rev_round 9
#define Turn_round 11 

#define NUM_LEDS          26   
#define num0     51
#define num1   31
#define num3 16
#define num4 12
#define INDICATOR_MS      30
#define BRIGHTNESS        255
#define STRIPLED_W  8
#define STRIPLED_H  8

// LED arrays for the lights
CRGB tur[NUM_LEDS];
CRGB rev[num1];
CRGB run_b[num0];
CRGB rev_round[num3];
CRGB leds[STRIPLED_W*STRIPLED_H];
CRGB turn_round[num4];

StripDisplay strip(STRIPLED_GPIO, STRIPLED_W, STRIPLED_H, WRAP_COLUMNS, ORIGIN_BOTTOM_LEFT, leds);

uint8_t indicatorLEDsLit = 0;

void indicatorAnimation(CRGB *leds) {
  for (int i = 0; i < indicatorLEDsLit; i++) {
    leds[i] = CRGB::Orange;
  }
  
  EVERY_N_MILLISECONDS(INDICATOR_MS) {
    indicatorLEDsLit++;
    if (indicatorLEDsLit > NUM_LEDS) indicatorLEDsLit = NUM_LEDS;
  }
}

void setup() {
  FastLED.addLeds<NEOPIXEL,STRIPLED_GPIO>(leds, STRIPLED_W*STRIPLED_H);
  strip.setup(fontP);
  Serial.begin(9600);
  Serial.println(String(STRIPLED_W*STRIPLED_H) + String(" leds on gpio ") + String(strip.getGpio()));

FastLED.addLeds<WS2812B, Tur, GRB>(tur, NUM_LEDS).setCorrection(TypicalLEDStrip);
FastLED.addLeds<WS2812B, Rev, GRB>(rev, num1).setCorrection(TypicalLEDStrip);  
FastLED.addLeds<WS2812, Rev_round, GRB>(rev_round, num3).setCorrection(TypicalLEDStrip);
FastLED.addLeds<WS2812, Turn_round, GRB>(turn_round, num4).setCorrection(TypicalLEDStrip);
  FastLED.setBrightness(BRIGHTNESS);

  pinMode(Brake, INPUT);
  pinMode(Running, INPUT);
  pinMode(Turn, INPUT);
  pinMode(Reverse, INPUT);
}

void loop() {
  strip.setFgColor(CRGB::White);
  strip.setBgColor(CRGB::Purple);

 

  // text scrolling example
  strip.setAlignment(ALIGN_LEFT);

  strip.setText(" Boaztheostrich");
  for (int offset=0; offset<strip.getTextWidth(); offset++) {
    strip.displayText(offset);
    FastLED.setBrightness(10);
    FastLED.delay(200);
     
}
}

**Comment by Boaztheostrich** [comment]
It seems to be memory related somehow, even without the warning showing up. But if I use smaller font 4x6 vs 5x8 it runs. 

The main issue is that this is not the entirety of my code

**Comment by lyriarte** [comment]
Hi @Boaztheostrich 

Seems like a memory issue to me, especially if the smaller font works. Actually I never tried on a arduino nano with so many strips connected, there may be side effects I haven't thought of. Nonetheless it's supposed to work, you are doing everything correctly, including using the FONT_CHARSET_SMALL define to strip parts of the charset.

One thing you can try is using the lower level APIs as in the [stacking example, lines 54 to 58](https://github.com/lyriarte/StripDisplay/blob/master/examples/Stacking/Stacking.ino#L54). The higher level [StripDisplay::displayText](https://github.com/lyriarte/StripDisplay/blob/master/StripDisplay.cpp#L227) API is not allocating extra memory but maybe this can help pinpoint the issue.

**Comment by Boaztheostrich** [comment]
I may try that thanks!
